"""Which sequences the fused kernels are allowed to answer for.

An event stream reaches the kernels through ``_pack_events``, which carries
timing, flip angle, phase and a per-event action word -- and the action word is
read off the description like everything else, so a sequence nobody shipped a
policy for packs and runs. What the kernels cannot answer for is a policy that
manipulates the states itself: it knows something the description does not, and
would run to a different answer than the operator loop.
"""

import pytest
import torch

from torchsim import TissueProperties, epg, fse_description
from torchsim.sequence._description import RfUse
from torchsim.sequence._simulation import EpgSimulator, make_simulator

ECHOES = 8
STATES = 10


def _describe():
    return fse_description(
        torch.deg2rad(torch.full((ECHOES,), 140.0)),
        echo_spacing_s=5e-3,
        phases_rad=torch.pi / 2,
    )


def _tissue():
    return TissueProperties(
        t1_ms=torch.tensor([800.0, 1400.0]), t2_ms=torch.tensor([45.0, 120.0])
    )


class _Unknown(EpgSimulator):
    """A sequence of a user's own, crushing around every refocusing pulse."""

    name = "a-policy-of-my-own"

    def before_rf(self, states, event):
        if event.rf_use is RfUse.REFOCUSING:
            return epg.shift(states)
        return states


@pytest.mark.parametrize(
    "name", ["fse", "spgr", "ssfp-fid", "ssfp-echo", "bssfp"]
)
def test_every_shipped_policy_reaches_the_kernels(name):
    """A description packs and runs, whichever policy is driving it -- and to
    the same answer, because both routes read the actions it carries.
    """
    simulator = make_simulator(name)
    loop = simulator.simulate(
        _describe(), _tissue(), backend="torch", nstates=STATES
    ).signal
    fused = simulator.simulate(
        _describe(), _tissue(), backend="native", nstates=STATES
    ).signal

    scale = loop.abs().max()
    assert scale > 0.0
    assert ((loop - fused).abs().max() / scale) < 1e-5


def test_a_policy_the_packing_does_not_know_is_refused():
    """Asked for outright, it must say so rather than answer differently."""
    with pytest.raises(RuntimeError, match="native EPG backend is unavailable"):
        _Unknown().simulate(
            _describe(), _tissue(), backend="native", nstates=STATES
        )


def test_a_policy_the_packing_does_not_know_still_simulates():
    """Left to choose, it takes the path that has the sequence's own state rules."""
    simulator = _Unknown()
    automatic = simulator.simulate(
        _describe(), _tissue(), backend="auto", nstates=STATES
    ).signal
    loop = simulator.simulate(
        _describe(), _tissue(), backend="torch", nstates=STATES
    ).signal

    assert torch.equal(automatic, loop)


# --- a sequence nobody shipped a policy for ---


def _handmade():
    """A refocused train written out by hand, saying what it plays.

    Nothing about it names a policy: this is the shape an autogenerated
    description arrives in, and the point of carrying the action word is that
    it reaches the kernels anyway.
    """
    from torchsim.sequence import EventAction
    from torchsim.sequence._description import (
        AdcRole,
        SequenceDescription,
        SequenceEvent,
    )
    from torchsim.sequence._builders import _unit_flip_definition

    events = [SequenceEvent.rf(0.0, 0, RfUse.EXCITATION, torch.pi / 2, torch.pi / 2)]
    for index in range(ECHOES):
        centre = 5e3 * (index + 1)
        events.append(
            SequenceEvent.rf(
                centre - 2.5e3,
                0,
                RfUse.REFOCUSING,
                torch.deg2rad(torch.tensor(140.0)),
                torch.pi / 2,
                action=EventAction.CRUSH_BEFORE | EventAction.CRUSH_AFTER,
            )
        )
        events.append(
            SequenceEvent.adc(centre, AdcRole.ECHO_CENTER, torch.pi / 2, is_echo=True)
        )
    return SequenceDescription(
        subsequence_index=0,
        tr_duration_us=5e3 * (ECHOES + 1),
        events=tuple(events),
        rf_definitions={0: _unit_flip_definition()},
    )


def test_a_sequence_with_no_shipped_policy_reaches_the_kernels():
    """The payoff: the description says what it plays, so the base policy --
    which knows nothing at all -- packs straight onto the fused kernels and
    lands where the operator loop does.
    """
    simulator = EpgSimulator()
    fused = simulator.simulate(
        _handmade(), _tissue(), backend="native", nstates=STATES
    ).signal
    loop = simulator.simulate(
        _handmade(), _tissue(), backend="torch", nstates=STATES
    ).signal

    scale = loop.abs().max()
    assert scale > 0.0
    assert ((loop - fused).abs().max() / scale) < 1e-5


def test_the_crushers_are_what_the_description_says_and_not_the_policy():
    """Strip the action off every event and the same policy must record a
    different train -- otherwise the action word is not what is being read.
    """
    from dataclasses import replace

    from torchsim.sequence import EventAction

    described = _handmade()
    bare = replace(
        described,
        events=tuple(
            replace(event, action=EventAction.NONE) for event in described.events
        ),
    )
    arguments = dict(backend="native", nstates=STATES)

    crushed = EpgSimulator().simulate(described, _tissue(), **arguments).signal
    plain = EpgSimulator().simulate(bare, _tissue(), **arguments).signal

    assert crushed.abs().max() > 0.0
    assert (crushed - plain).abs().max() > 1e-3 * crushed.abs().max()


def test_a_policy_that_moves_the_states_itself_is_still_refused():
    """The name gate is gone; what refuses now is a policy carrying rules the
    description does not.
    """
    assert not EpgSimulator()._carries_own_rules()
    assert not make_simulator("fse")._carries_own_rules()
    assert _Unknown()._carries_own_rules()
