"""Sequence descriptions and differentiable state-machine simulation."""

from __future__ import annotations

__all__ = [
    "AdcRole",
    "ExactSliceProfile",
    "EventAction",
    "EventType",
    "RfDefinition",
    "RfMode",
    "RfShape",
    "RfUse",
    "SequenceDescription",
    "SequenceEvent",
    "ShimDefinition",
    "EpgEngine",
    "SimulationResult",
    "SubspaceBasis",
    "TissueProperties",
    "calibrate",
    "decompress_shape",
    "execution",
    "FSEReadout",
    "Operator",
    "bSSFPReadout",
    "compose",
    "Delay",
    "Dephase",
    "distribute",
    "exact_slice_profile",
    "Excitation",
    "fse_description",
    "ideal_rf_definition",
    "Inversion",
    "module",
    "operator",
    "operator_names",
    "mpnrage_description",
    "mprage_description",
    "mrf_description",
    "offload",
    "Readout",
    "Refocusing",
    "register_operator",
    "Saturation",
    "simulate_subspace",
    "SPGRReadout",
    "Spoil",
    "SSFPFidReadout",
    "spgr_description",
]

from ._accelerators import distribute, execution, offload
from ._calibration import calibrate
from ._builders import (
    fse_description,
    mpnrage_description,
    mprage_description,
    mrf_description,
    spgr_description,
)
from ._operators import (
    FSEReadout,
    Operator,
    bSSFPReadout,
    compose,
    Delay,
    Dephase,
    Excitation,
    Inversion,
    module,
    operator,
    operator_names,
    Readout,
    Refocusing,
    register_operator,
    Saturation,
    SPGRReadout,
    Spoil,
    SSFPFidReadout,
)
from ._description import (
    AdcRole,
    EventAction,
    EventType,
    ideal_rf_definition,
    RfDefinition,
    RfMode,
    RfShape,
    RfUse,
    SequenceDescription,
    SequenceEvent,
    ShimDefinition,
    decompress_shape,
)
from ._transition import ExactSliceProfile, exact_slice_profile
from ._simulation import (
    EpgEngine,
    SimulationResult,
    SubspaceBasis,
    TissueProperties,
    simulate_subspace,
)
