"""Sequence descriptions and differentiable state-machine simulation."""

from __future__ import annotations

__all__ = [
    "AdcRole",
    "ExactSliceProfile",
    "EventAction",
    "EventType",
    "RfDefinition",
    "RfMode",
    "RfShape",
    "RfUse",
    "SequenceDescription",
    "SequenceEvent",
    "ShimDefinition",
    "EpgEngine",
    "SimulationResult",
    "SubspaceBasis",
    "TissueProperties",
    "calibrate",
    "decompress_shape",
    "execution",
    "Operator",
    "bssfp_readout",
    "compose",
    "delay",
    "dephase",
    "distribute",
    "exact_slice_profile",
    "excitation",
    "fse_description",
    "ideal_rf_definition",
    "inversion",
    "module",
    "operator",
    "operator_names",
    "mpnrage_description",
    "mprage_description",
    "mrf_description",
    "offload",
    "readout",
    "refocusing",
    "register_operator",
    "saturation",
    "simulate_subspace",
    "spgr_readout",
    "spoil",
    "ssfp_fid_readout",
    "spgr_description",
]

from ._accelerators import distribute, execution, offload
from ._calibration import calibrate
from ._builders import (
    fse_description,
    mpnrage_description,
    mprage_description,
    mrf_description,
    spgr_description,
)
from ._operators import (
    Operator,
    bssfp_readout,
    compose,
    delay,
    dephase,
    excitation,
    inversion,
    module,
    operator,
    operator_names,
    readout,
    refocusing,
    register_operator,
    saturation,
    spgr_readout,
    spoil,
    ssfp_fid_readout,
)
from ._description import (
    AdcRole,
    EventAction,
    EventType,
    ideal_rf_definition,
    RfDefinition,
    RfMode,
    RfShape,
    RfUse,
    SequenceDescription,
    SequenceEvent,
    ShimDefinition,
    decompress_shape,
)
from ._transition import ExactSliceProfile, exact_slice_profile
from ._simulation import (
    EpgEngine,
    SimulationResult,
    SubspaceBasis,
    TissueProperties,
    simulate_subspace,
)
